### ISSUE TITLE
Use clang?

### ISSUE THREAD

**Issue by x1957** [lgarithm/drawings#7]
Is there any problems with using clang?

**Comment by lgarithm** [comment]
I developed it on mac, so it works best with clang.
But there are some issues with lower version of GCC:
i). keyword **override** not supported (at least not support at 4.6)
ii). regex not fully supported until 4.9

**Comment by lgarithm** [comment]
some new features of template also not well supported in GCC, like keyword **using**
So the linear module had been reimplemented in macro.
